// I Ching data -- the 64 hexagrams in King Wen order.
//
// The names, Chinese characters and trigram structure are the traditional
// ones. The keywords, summaries and advice below are original, concise
// wording written for this app (no translation text is reproduced).

// Trigrams. `lines` are listed bottom to top: 1 = solid (yang), 0 = broken (yin).
const TRIGRAMS = {
  qian: { name: "Qián", image: "Heaven", char: "☰", lines: [1, 1, 1] },
  kun: { name: "Kūn", image: "Earth", char: "☷", lines: [0, 0, 0] },
  zhen: { name: "Zhèn", image: "Thunder", char: "☳", lines: [1, 0, 0] },
  kan: { name: "Kǎn", image: "Water", char: "☵", lines: [0, 1, 0] },
  gen: { name: "Gèn", image: "Mountain", char: "☶", lines: [0, 0, 1] },
  xun: { name: "Xùn", image: "Wind", char: "☴", lines: [0, 1, 1] },
  li: { name: "Lí", image: "Fire", char: "☲", lines: [1, 0, 1] },
  dui: { name: "Duì", image: "Lake", char: "☱", lines: [1, 1, 0] },
};

// [upper trigram, lower trigram] for hexagrams 1..64 (King Wen sequence).
const KING_WEN_TRIGRAMS = [
  ["qian", "qian"], ["kun", "kun"], ["kan", "zhen"], ["gen", "kan"],
  ["kan", "qian"], ["qian", "kan"], ["kun", "kan"], ["kan", "kun"],
  ["xun", "qian"], ["qian", "dui"], ["kun", "qian"], ["qian", "kun"],
  ["qian", "li"], ["li", "qian"], ["kun", "gen"], ["zhen", "kun"],
  ["dui", "zhen"], ["gen", "xun"], ["kun", "dui"], ["xun", "kun"],
  ["li", "zhen"], ["gen", "li"], ["gen", "kun"], ["kun", "zhen"],
  ["qian", "zhen"], ["gen", "qian"], ["gen", "zhen"], ["dui", "xun"],
  ["kan", "kan"], ["li", "li"], ["dui", "gen"], ["zhen", "xun"],
  ["qian", "gen"], ["zhen", "qian"], ["li", "kun"], ["kun", "li"],
  ["xun", "li"], ["li", "dui"], ["kan", "gen"], ["zhen", "kan"],
  ["gen", "dui"], ["xun", "zhen"], ["dui", "qian"], ["qian", "xun"],
  ["dui", "kun"], ["kun", "xun"], ["dui", "kan"], ["kan", "xun"],
  ["dui", "li"], ["li", "xun"], ["zhen", "zhen"], ["gen", "gen"],
  ["xun", "gen"], ["zhen", "dui"], ["zhen", "li"], ["li", "gen"],
  ["xun", "xun"], ["dui", "dui"], ["xun", "kan"], ["kan", "dui"],
  ["xun", "dui"], ["zhen", "gen"], ["kan", "li"], ["li", "kan"],
];

// [character, pinyin, English name, keywords, meaning, advice]
const HEXAGRAM_TEXTS = [
  ["乾", "Qián", "The Creative", ["strength", "initiative", "vision", "leadership"],
    "Pure creative force. Energy is high and the way is open, but power works best when it is steady and directed rather than forced.",
    "Act with confidence, stay consistent, and keep your ambition tied to a purpose."],
  ["坤", "Kūn", "The Receptive", ["receptivity", "devotion", "support", "patience"],
    "Yielding strength. Progress comes by following, supporting and nourishing rather than leading or pushing.",
    "Be adaptable and generous, let others set the pace, and let things ripen."],
  ["屯", "Zhūn", "Difficulty at the Beginning", ["chaos", "sprouting", "persistence", "help"],
    "Something new is straining to grow, and the start is messy and uncertain. Confusion at this stage is normal, not a sign of failure.",
    "Do not rush. Build a little structure, ask for help, and take one small step at a time."],
  ["蒙", "Méng", "Youthful Folly", ["inexperience", "learning", "curiosity", "guidance"],
    "You are a beginner, or you are guiding one. Real learning starts with humility and sincere questions.",
    "Ask honestly, listen well, and do not ask the same question twice in the hope of a different answer."],
  ["需", "Xū", "Waiting", ["patience", "timing", "trust", "nourishment"],
    "The way ahead is not yet clear or safe. Waiting here is active: you gather strength and keep your confidence while the moment ripens.",
    "Stay calm, look after yourself, and act when the timing is right."],
  ["訟", "Sòng", "Conflict", ["dispute", "friction", "caution", "compromise"],
    "Opposing positions are hardening. Winning the argument may cost more than settling it.",
    "Stay fair, avoid escalating, and seek a neutral party or a compromise."],
  ["師", "Shī", "The Army", ["discipline", "organization", "leadership", "collective effort"],
    "A shared effort needs order, a clear aim and a trusted leader. Discipline serves a cause; without one it becomes mere force.",
    "Get organized, keep the goal fair and clear, and avoid needless battles."],
  ["比", "Bǐ", "Holding Together", ["union", "loyalty", "alliance", "sincerity"],
    "People draw together and support one another. Lasting bonds are built on openness and shared commitment, not on convenience.",
    "Choose your allies carefully, join in sincerely, and do not wait too long to commit."],
  ["小畜", "Xiǎo Chù", "Small Taming", ["restraint", "small gains", "gathering", "gentle influence"],
    "Small, patient influence accumulates. Forces are gathering but not yet strong enough for a bold move.",
    "Make modest progress, refine details, and be gentle with obstacles."],
  ["履", "Lǚ", "Treading", ["conduct", "care", "boldness", "etiquette"],
    "You are walking close to something powerful. Good manners, awareness and calm confidence keep you safe.",
    "Move with care and respect, stay true to your principles, and do not provoke the strong."],
  ["泰", "Tài", "Peace", ["harmony", "prosperity", "flow", "good fortune"],
    "Heaven and earth are in communication and things flow. It is a time of ease and growth, but it will not last without upkeep.",
    "Make good use of the season, share what you have, and do not get careless."],
  ["否", "Pǐ", "Standstill", ["stagnation", "blockage", "withdrawal", "endurance"],
    "Communication has broken down and efforts stall. It is a poor time to push; it is a good time to hold to your values.",
    "Conserve your energy, stay true to yourself, and wait for the tide to turn."],
  ["同人", "Tóng Rén", "Fellowship", ["community", "cooperation", "openness", "shared goals"],
    "People unite around a common purpose beyond narrow interests. Success comes from working in the open with those who share your aim.",
    "Reach out, drop your cliques, and build on what you have in common."],
  ["大有", "Dà Yǒu", "Great Possession", ["abundance", "success", "generosity", "clarity"],
    "You hold a great deal, whether resources, influence or opportunity. It stays good when it is used modestly and for the common good.",
    "Be generous, stay humble, and use what you have wisely."],
  ["謙", "Qiān", "Modesty", ["humility", "balance", "restraint", "quiet strength"],
    "True worth does not need to announce itself. Modesty evens things out and earns lasting respect.",
    "Play down your achievements, give credit freely, and finish what you start."],
  ["豫", "Yù", "Enthusiasm", ["momentum", "joy", "preparation", "inspiration"],
    "Energy and morale are high and people move together. Enthusiasm carries you further when it is grounded in preparation.",
    "Channel the excitement into action, but do not let it become complacency."],
  ["隨", "Suí", "Following", ["adaptability", "flexibility", "trust", "timing"],
    "Leadership comes through knowing when to follow. Adapting to circumstances and to worthy people brings support.",
    "Adjust to the situation, follow what is good, and be sure who you are following."],
  ["蠱", "Gǔ", "Repairing Decay", ["neglect", "renewal", "responsibility", "cleanup"],
    "Something inherited has been left to spoil. The mess can be traced to neglect, and it can also be fixed.",
    "Find the root cause, clean it up thoroughly, and give the repair careful thought at both ends."],
  ["臨", "Lín", "Approach", ["arrival", "growth", "attention", "opportunity"],
    "Something great is approaching and momentum is building. The favorable period is real but not permanent.",
    "Move forward with care and sincerity, and do not let confidence outrun preparation."],
  ["觀", "Guān", "Contemplation", ["observation", "perspective", "example", "reflection"],
    "Step back and see the bigger picture. Your conduct is being watched, and being still in thought clarifies your view.",
    "Observe before acting and lead by example rather than by instruction."],
  ["噬嗑", "Shì Kè", "Biting Through", ["resolution", "justice", "obstacle", "decisiveness"],
    "Something stands in the way and must be dealt with firmly. Clear judgment and fair enforcement remove the blockage.",
    "Face the problem directly, be fair but firm, and do not let it drag on."],
  ["賁", "Bì", "Grace", ["beauty", "form", "polish", "appearance"],
    "Form and presentation matter, but they adorn substance rather than replace it. Beauty is welcome in small things.",
    "Make a good impression, but do not mistake polish for the real thing."],
  ["剝", "Bō", "Splitting Apart", ["decline", "erosion", "letting go", "stillness"],
    "Structures wear away and what was built on weak ground falls. It is not the time to act boldly.",
    "Let go of what is falling, stay put, and preserve what is essential."],
  ["復", "Fù", "Return", ["renewal", "turning point", "recovery", "new cycle"],
    "The light returns after a dark period. A fresh start comes quietly, and it needs gentle handling.",
    "Begin again without haste, welcome the change and nurture the new seed."],
  ["無妄", "Wú Wàng", "Innocence", ["spontaneity", "sincerity", "integrity", "the unexpected"],
    "Acting from a pure, unscheming heart is the safest course. Calculation and hidden motives backfire.",
    "Be natural and honest, follow your true nature and avoid manipulation."],
  ["大畜", "Dà Chù", "Great Taming", ["accumulation", "restraint", "potential", "study"],
    "Great strength is being held in reserve and built up. Learning, discipline and patience prepare a bigger undertaking.",
    "Keep building your knowledge and resources, and hold back until the time is right."],
  ["頤", "Yí", "Nourishment", ["nourishment", "diet", "words", "self-care"],
    "What you take in, physically, mentally or in what you say, shapes what you become. Look after the source of your nourishment.",
    "Watch what you consume and what you say, and feed the parts of you that matter."],
  ["大過", "Dà Guò", "Great Excess", ["overload", "pressure", "extremes", "decisive action"],
    "The load is too heavy for the beam. It is an extraordinary time that calls for an unusual response.",
    "Act boldly but sensibly, shore up the weak point and do not go it alone."],
  ["坎", "Kǎn", "The Abyss", ["danger", "depth", "sincerity", "perseverance"],
    "You are in a deep or dangerous place, but water keeps flowing through it without losing its nature. Sincerity and steadiness carry you through.",
    "Do not resist the danger, stay true to yourself and keep moving."],
  ["離", "Lí", "The Clinging Fire", ["clarity", "illumination", "dependence", "awareness"],
    "Fire depends on what it burns and clarity depends on what it clings to. Attach yourself to something worthy and your vision brightens.",
    "Cultivate clear thinking, stay connected to what nourishes you and be warm with others."],
  ["咸", "Xián", "Influence", ["attraction", "courtship", "receptivity", "connection"],
    "Mutual attraction and sensitivity draw two together. Influence works through openness, not pressure.",
    "Stay open and sincere, respond rather than push, and let the connection develop."],
  ["恆", "Héng", "Duration", ["endurance", "constancy", "commitment", "stability"],
    "Lasting things keep moving within a stable framework. Constancy does not mean rigidity: it means holding to a direction while adapting.",
    "Commit to the long run, keep your purpose steady and adapt the means."],
  ["遯", "Dùn", "Retreat", ["withdrawal", "strategy", "timing", "preservation"],
    "When circumstances turn against you, a well-timed retreat is a form of strength. Withdraw with dignity while you still can.",
    "Step back without bitterness, save your strength and keep your principles."],
  ["大壯", "Dà Zhuàng", "Great Power", ["strength", "momentum", "restraint", "righteousness"],
    "You have great power and momentum. Strength is only worthwhile when it is guided by principle, so it needs restraint.",
    "Use your strength for the right things, avoid bullying and do not overreach."],
  ["晉", "Jìn", "Progress", ["advancement", "recognition", "clarity", "rising"],
    "Like the sun rising over the earth, your progress becomes visible. Recognition comes to a steady and honest effort.",
    "Move ahead openly, accept the attention gracefully and keep serving the whole."],
  ["明夷", "Míng Yí", "Darkening of the Light", ["adversity", "concealment", "endurance", "inner light"],
    "A dark time in which showing your brightness is risky. Preserve your inner light and stay quiet rather than fight what you cannot beat.",
    "Keep your integrity private, avoid open confrontation and wait it out."],
  ["家人", "Jiā Rén", "The Family", ["household", "roles", "loyalty", "sincerity"],
    "The health of the whole grows from the home. Clear roles, sincerity and care within the closest circle set the tone for everything else.",
    "Attend to your home and inner circle, keep your words and actions consistent."],
  ["睽", "Kuí", "Opposition", ["divergence", "tension", "difference", "small steps"],
    "Views and directions are pulling apart. Yet differences can complement each other, and small cooperation still works.",
    "Do not force agreement, look for common ground in small matters and be patient."],
  ["蹇", "Jiǎn", "Obstruction", ["obstacle", "reflection", "retreat", "help"],
    "A hard barrier blocks your way. Pushing ahead is not wise; step back, reflect on yourself and seek support.",
    "Look inward, ask for wise counsel, and go around instead of through."],
  ["解", "Xiè", "Deliverance", ["release", "relief", "resolution", "moving on"],
    "Tension breaks like a storm clearing the air. Problems loosen, and the best response is to act quickly and then let them go.",
    "Deal with what remains, forgive readily, and return to normal life."],
  ["損", "Sǔn", "Decrease", ["simplifying", "sacrifice", "sincerity", "essentials"],
    "Reducing the outer to strengthen the inner. A modest, sincere offering carries more weight than a lavish one.",
    "Cut back on the unnecessary and give sincerely, not extravagantly."],
  ["益", "Yì", "Increase", ["benefit", "growth", "generosity", "opportunity"],
    "A favorable time when giving and improving pay off for everyone. Big steps are supported, so use the momentum.",
    "Take on worthwhile projects, share your gains and correct your faults."],
  ["夬", "Guài", "Breakthrough", ["resolve", "decision", "exposure", "vigilance"],
    "A long-brewing situation reaches its moment of resolution. Deal with it openly and firmly, without violence or hatred.",
    "Speak plainly, act decisively but calmly, and stay alert to what is left."],
  ["姤", "Gòu", "Coming to Meet", ["encounter", "temptation", "surprise", "caution"],
    "An unexpected meeting arrives, and it may be more forceful than it looks. Not every attractive encounter is good for you.",
    "Be careful about what you let in, and do not commit before you know the whole picture."],
  ["萃", "Cuì", "Gathering Together", ["assembly", "community", "purpose", "preparation"],
    "People come together around a shared center. A gathering needs a worthy purpose and good organization to hold.",
    "Bring people together, stay sincere and be ready for the unexpected."],
  ["升", "Shēng", "Pushing Upward", ["growth", "steady ascent", "effort", "support"],
    "Steady, patient effort brings a rise, like a plant pushing through soil. Progress is gradual and supported.",
    "Keep climbing at a steady pace, accept help and do not hurry."],
  ["困", "Kùn", "Oppression", ["exhaustion", "confinement", "endurance", "integrity"],
    "You are worn down and hemmed in, and words alone will not help. Adversity tests what you are made of.",
    "Stay cheerful and firm inside, conserve your energy and do not argue your case."],
  ["井", "Jǐng", "The Well", ["source", "resource", "community", "maintenance"],
    "A well serves everyone and does not run dry, but it needs upkeep. The source of support must be looked after.",
    "Go back to basics, maintain what nourishes you and share it."],
  ["革", "Gé", "Revolution", ["change", "transformation", "timing", "renewal"],
    "The old order has outlived its use and change is due. Radical change succeeds when the time is right and the cause is fair.",
    "Prepare carefully, win trust before you act and change decisively."],
  ["鼎", "Dǐng", "The Cauldron", ["transformation", "nourishment", "culture", "refinement"],
    "A vessel that turns raw material into nourishment. It stands for refined values and the transmission of what is best.",
    "Make good use of your talents, prize excellence and share the results."],
  ["震", "Zhèn", "The Arousing", ["shock", "awakening", "alertness", "composure"],
    "Sudden shock, like thunder, jolts you awake. The fright passes quickly and leaves you more alert.",
    "Stay calm when startled, use the wake-up call and examine your conduct."],
  ["艮", "Gèn", "Keeping Still", ["stillness", "meditation", "stopping", "boundaries"],
    "A time to stop, like a mountain. Quieting the mind and holding back from restless action gives clarity.",
    "Pause, find your stillness and act only when you know it is the right moment."],
  ["漸", "Jiàn", "Gradual Development", ["gradual progress", "patience", "steadiness", "courtship"],
    "Growth that unfolds step by step, like a tree on a hillside. Lasting results cannot be hurried.",
    "Take it slowly, build a solid foundation and trust the process."],
  ["歸妹", "Guī Mèi", "The Marrying Maiden", ["subordination", "impulse", "position", "caution"],
    "A connection made from an awkward or subordinate position. Ends and beginnings are tangled, and good feelings alone do not settle matters.",
    "Look at where you stand, avoid rushing and keep your dignity."],
  ["豐", "Fēng", "Abundance", ["peak", "fullness", "clarity", "impermanence"],
    "A moment of fullness and brightness, the height of the cycle. Enjoy it and use it, remembering that it will pass.",
    "Make the most of it, be fair-minded, and do not cling to the peak."],
  ["旅", "Lǚ", "The Wanderer", ["travel", "transience", "caution", "modesty"],
    "You are far from home or without firm footing. Be modest, careful and adaptable, since you cannot rely on your usual support.",
    "Keep a low profile, be courteous and do not overstay your welcome."],
  ["巽", "Xùn", "The Gentle Wind", ["gentleness", "penetration", "persistence", "subtlety"],
    "Like the wind, gentle but persistent influence gets in everywhere. Repeated, quiet effort wins where force cannot.",
    "Be subtle and persistent, make your purpose clear and seek wise counsel."],
  ["兌", "Duì", "The Joyous Lake", ["joy", "conversation", "friendship", "openness"],
    "Joy that comes from real connection and honest exchange. It is strongest when it is shared and rooted in sincerity.",
    "Enjoy good company, speak warmly and honestly, and avoid flattery."],
  ["渙", "Huàn", "Dispersion", ["dissolving", "release", "reunion", "letting go"],
    "Rigid barriers and tensions dissolve. Loosening what has become stuck, including ego, makes reunion possible.",
    "Let go of stubbornness, dissolve what divides you and rebuild around a shared purpose."],
  ["節", "Jié", "Limitation", ["boundaries", "moderation", "discipline", "budget"],
    "Limits give shape to freedom. Sensible boundaries protect resources and focus, but harsh ones are hard to bear.",
    "Set reasonable limits, live within your means and stay flexible."],
  ["中孚", "Zhōng Fú", "Inner Truth", ["sincerity", "trust", "openness", "influence"],
    "A sincere, open heart can move even the hard to reach. Trust that is real is felt, not argued.",
    "Be honest and unguarded, act from your true center and let trust do its work."],
  ["小過", "Xiǎo Guò", "Small Excess", ["small things", "modesty", "caution", "detail"],
    "Small matters are favored over large ones. Be a little more careful, humble or restrained than usual.",
    "Stay with the everyday, do not aim too high and pay attention to details."],
  ["既濟", "Jì Jì", "After Completion", ["completion", "vigilance", "maintenance", "order"],
    "Everything is in place, and that is exactly when decline can begin. Success needs care to keep it.",
    "Stay alert, tend what you have achieved and prepare for change."],
  ["未濟", "Wèi Jì", "Before Completion", ["almost", "transition", "caution", "hope"],
    "Not quite there. You are close to your goal, but the last step is the trickiest and calls for care.",
    "Do not celebrate early, look before you leap and finish what you started."],
];

// Meaning of each line position in a hexagram (bottom to top). Original
// generic wording -- the same for every hexagram.
const LINE_POSITIONS = [
  { name: "First line", theme: "The beginning", text: "The root of the matter: early stirrings, foundations, and what has not yet shown itself." },
  { name: "Second line", theme: "The inner circle", text: "Your immediate surroundings and steady supports: how things work at close range." },
  { name: "Third line", theme: "The threshold", text: "A point of tension between inner and outer, often a test or a restless push forward." },
  { name: "Fourth line", theme: "The approach", text: "Stepping into wider circles or nearer to authority; caution and good relationships matter here." },
  { name: "Fifth line", theme: "The center of power", text: "The place of influence and clear leadership: where the situation is most fully expressed." },
  { name: "Sixth line", theme: "The culmination", text: "The far edge of the situation: completion, overreach, or letting go." },
];

// Builds full hexagram objects (with trigram references and line patterns).
const HEXAGRAMS = HEXAGRAM_TEXTS.map(
  ([char, pinyin, name, keywords, meaning, advice], i) => {
    const [upperKey, lowerKey] = KING_WEN_TRIGRAMS[i];
    return {
      number: i + 1,
      char,
      pinyin,
      name,
      keywords,
      meaning,
      advice,
      upper: upperKey,
      lower: lowerKey,
      // bottom to top, 1 = solid, 0 = broken
      lines: [...TRIGRAMS[lowerKey].lines, ...TRIGRAMS[upperKey].lines],
    };
  },
);

// Look up a hexagram from six bottom-to-top line values (1 solid / 0 broken).
const hexagramFromLines = (lines) =>
  HEXAGRAMS.find((h) => h.lines.every((v, i) => v === lines[i]));
